spring: 
  profiles:
    active:
    - mariadb
---    
spring: 
  profiles: cloudConfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hongju213/CloudConfig.git
---          
#서버포트 설정
server:
  port: 8085
  
---
#mariadb 정보  

spring: 
  profiles: mariadb
  datasource:
   driverClassName: org.mariadb.jdbc.Driver
   url: jdbc:mariadb://192.168.10.230:3306/PCtracking
   username: mmifEnZiCtCB+s8SZLmpEU70exBLvwX2
   password: QVY2bVLPhaIgGxTugs63ZGCge1tZtzdS
   
---


#Log 설정   
logging:
  config: classpath:spring/logback-spring.xml

#JSP 연결 설정  
spring:
 mvc:
  view:
   prefix:  /WEB-INF/views/
   suffix: .jsp
  static-path-pattern: /main/webapp/**
  
